Algoritmo "ExEntradaProcessamentoSaida"

Var
num1: real
num2: real
num3: real

soma: real
media: real


Inicio
Escreval ("Digite o primeiro número")
Leia (num1)

Escreval ("Digite o segundo número")
Leia (num2)

Escreval ("Digite o terceiro número")
Leia (num3)

soma <- num1 + num2 + num3
media <- soma / 3

Escreval ("Primeiro número digitado ", num1)
Escreval ("Segundo número digitado ", num2)
Escreval ("Resultado da Soma: ", soma)
Escreval ("Resultado da Média ", media)

Fimalgoritmo