Algoritmo "VETORNOME"

Var
nomes: vetor [1..5] de caractere
contadorLoop1: inteiro


Inicio
para contadorLoop1 de 1 ate 5 faca
    escreva ("Digite o nome do aluno(a) número: ", contadorLoop1, "de 5:")
    leia (nomes[contadorLoop1])
fimpara

     
//Apresentação do resultado
para contadorLoop1 de 1 ate 5 faca
    escreval ("Nome do(a) aluno(a): ", nomes[contadorLoop1])
     
fimpara

Fimalgoritmo